apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-rw.keycloak.svc.cluster.local
    port: 5432
    database: keycloak
    usernameSecret:
      name: postgres-secret
      key: username
    passwordSecret:
      name: postgres-secret
      key: password
  http:
    httpEnabled: true
    httpPort: 80
  hostname:
    hostname: sso.local.lan.vernal.dev
    adminUrl: https://sso.local.lan.vernal.dev/
    strict: false
    strictBackchannel: false
  ingress:
    enabled: false
