apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./internal
- ./operator
- ./resources
- ./crossplane.sealedsecret.yaml
- ./httproute.yaml
- ./keycloak.providerconfig.yaml
- ./keycloak.yaml
- ./master.realm.yaml
- ./namespace.yaml
- ./postgres.sealedsecret.yaml
- ./postgres.yaml
