apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgA8ibznKUgIOFNJzuHjBbqwjOgUUle/PrcCqJF6m7hOoEQcL7z70FHWNmtwtqPTlVUjoy5J1TnQjxornaU9tNd5/rP8XgmdqTTAaDagBPju15mDJL3KP9gfvwCBIoB1595dnTHfEdIBJ8x6DzQb01cZeSmnZx47N9GZHSMr59L0sG/OrFnqRpU3yR8WLRDLwQ+un48A6XIFnbIiKBtHpJpliL1ZFhIiaH/0g8k5zqccBoUgwCrOf60TlSfcIneZt6EgK/zjXMIjqaemQ+TEMSE/7uyNe/ct01+V19r7cAtvPjgFP3R0ggKfaszm+94jVas7suBumSjuj3qnXlNRzJbl0RDCGlrQc8mPuXbUV3HkFq8gre/8nGK+WtG9DdHAS/7AxDd/dCv94AAboFZkfdY3frEaVKQ8hez8Bsf2niG5DnVL8Ka4t6B12ia1jffAPafR4aPds2Qsns4K4+ivRtptgDTTsvN/oY4QMuNvBX1Q2L3R/0lwWrM1wJrtEvI3vWaTbjhUTEGxxaJdQ6cU+NJOuOuRZJl8wElP3UtZ/1/FubGyVYQfCtZJ3rURtj67at6xyORjZ8R4SBh5FnHg/XscyYIFZ22R/K0uzkTNoNOL7oeaGLrRxA1MVjBJodrKFtELJhh3992Uu5rAtmsWLN0RsLAQiRHeLMyKgqyp6eJqtj23XNSV2z+zxKuWQiD+c2aHFxY6glWybiua+Z4j0e8=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque

