apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  # Root settings
  GF_SECURITY_COOKIE_SECURE: "true"
  GF_SECURITY_COOKIE_SAMESITE: none
  GF_SECURITY_ALLOW_EMBEDDING: "true"
  GF_INSTANCE_NAME: vernal-grafana
  GF_SERVER_DOMAIN: grafana.local.lan.vernal.dev
  GF_SERVER_ROOT_URL: https://grafana.local.lan.vernal.dev

  # Image renderer
  # GF_RENDERING_SERVER_URL: http://grafana-image-renderer.grafana.svc.cluster.local:8081/render
  # GF_RENDERING_CALLBACK_URL: http://grafana.grafana.svc.cluster.local:3000/
  # GF_RENDERING_CONCURRENT_RENDER_REQUEST_LIMIT: "3"

  # Image storage
  # GF_EXTERNAL_IMAGE_STORAGE_PROVIDED: local

  # Install plugins
  GF_INSTALL_PLUGINS: grafana-piechart-panel

  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_NAME: Main Org.
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
