apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./https-redirect.httproute.yaml
- ./local-lan-vernal-dev.gateway.yaml
- ./namespace.yaml
- ./podmonitor.yaml
- ./servicemonitor.yaml

helmCharts:
- includeCRDs: true
  name: base
  namespace: istio-system
  releaseName: istio-base
  repo: https://istio-release.storage.googleapis.com/charts
  valuesFile: base.values.yaml
  version: 1.20.1
- includeCRDs: true
  name: istiod
  namespace: istio-system
  releaseName: istio-istiod
  repo: https://istio-release.storage.googleapis.com/charts
  valuesFile: istiod.values.yaml
  version: 1.20.1

patches:
- target:
    group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
    version: v1
  patch: |-
    - op: replace
      path: /webhooks/0/clientConfig/service/name
      value: istiod-1-20-1
