apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Applications hosted on local development clusters
  sourceRepos:
  - https://github.com/vernaldev/k8s-dev
  destinations:
  - server: "*"
    namespace: "*"
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
