apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- ./infra
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.1/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.12.2/manifests/install.yaml
- ./apps.appproject.yaml
- ./core.appproject.yaml
- ./dev-cluster.secret.yaml
- ./httproute.yaml
- ./k8s-dev.sealedsecret.yaml
- ./namespace.yaml
- ./service.yaml

patchesStrategicMerge:
- ./configmap.yaml

patches:
- target:
    version: v1
    kind: Deployment
    name: argocd-repo-server
  patch: |
    - op: remove
      path: /spec/template/spec/containers/0/securityContext/seccompProfile
- target:
    version: v1
    kind: Deployment
    name: argocd-image-updater
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/ports/0
      value:
        name: app
        containerPort: 8080
    - op: add
      path: /spec/template/spec/containers/0/ports/-
      value:
        name: metrics
        containerPort: 8082
- target:
    version: v1
    kind: Service
    name: argocd-applicationset-controller
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
- target:
    version: v1
    kind: Service
    name: argocd-dex-server
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5558"
- target:
    version: v1
    kind: Service
    name: argocd-metrics
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
- target:
    version: v1
    kind: Service
    name: argocd-notifications-controller-metrics
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
- target:
    version: v1
    kind: Service
    name: argocd-repo-server
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"
- target:
    version: v1
    kind: Service
    name: argocd-server-metrics
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
- target:
    kind: NetworkPolicy
    name: argocd-redis-network-policy
  patch: |
    - op: add
      path: /spec/egress/0/ports/-
      value:
        port: 15012
        protocol: TCP
