apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  keycloak.override: |
    rewrite name substring sso.local.lan.vernal.dev keycloak-secure.keycloak.svc.cluster.local
