apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgB6QImX1crZB9xXk5G0sjgZF+c2jjVQAQe0fxRWv2oNwwJmwItgbQZcz2D+Vh/u/jzrXvbByO/cddc/0PES9cMTZbszdOWxv3mLA2BSPsFzhiU9q3bzXmtPG8S0qEG+A/miT1K3g+fjsllY6SfRSuOPT4cmzqW0fA+zRW6xQ31z9ScYWHBTLWnEqFD1tX9IEs3Wl9T2ZAqc2OfMJsr0+aMT7xfgFHt5x4p1W2n4Ui2KPTiXxztFHF/8o/9HsDLh3cdZcjY8VyffMZKo5OzKwkQpqwKbwKnsyi3nrJanTx24V0I8cVfPxYt9aMilYSOQuQY5OZKeSOp94BLeLYijoeIiaMPEC9ozZ4vSAZGGmE+zLjPW3vwZn90SR01Lq77NMiku0b1Xg0jHppZGP7zEuJaUDJtzJL88MD6+UBJxn+DufFnvvcgAc/Mp1LWqoxywqQ5DX4gVFGkwgXXJVTTrS6imEcxYorMlQM/usM6E08FIurPU6gTEwp2+EqcbE76yi94NYxRUNZp0D6s0YwVMf4nMyHiPd7PkVCyYDEaHmXGOThEgyDJh8n0lu5NCn3/9+n9cHJY/hKr0YJdaZNLjALqvgfUS81JlYp9+9PnhBTPRnzYM9kZoAIbTcg5Wf8mSDvmaohdb92YyGgS8C0Y4qscSN+iwetfgwWo9yDnm0hrjKOaY2TjAQ68RhYI1qmhc5hHdFFc/JHrIT7OO7bQMApx5d9Z4avsHNTls3bsEq8WmSw==
    username: AgBazuG/kgKgT19yjxOUKlzrLWlCfGcUZ03E28DFHKnNqX/vj3ixmJL/IiauL9CGgEAGJtuvk+LzsCxcZe+itAgg55Jom/NSrUdMMRFsJr7cTh4ESvGX2qR59MluMxPov1sH48UmST+tlbOzDXYw2Bj7bq/scma6IRn+46RxKJZqPldJg6EqD3V6PCbw7NLuE5Tlf4NBmT305AwtwdaIjD2Uxd0DPnpKqJw9O5VI3qM6JzW/2qoGcRyllfZG0GW13jmFGxQKbLGPGymcubQHmN+rZvDhn7FnNqm+034GjQq+1GlgPCeWjcB+TK9WloXwizyvi/WAbV+jP85Qj7+i/eboF8weAEVHyo+OlUr+S1eL81kMKlpOD/b6BpQ6h9ULl/1cFukFaVeMniUSGrNbanpKwautLQjevBVLJeCeBaL54f2mjT2Q/bM+gH3rPXXFvcJzkWDEkMJ58jnN7q7oN3hUv//XYCLPhAdzvvCIq2ezR3aclI6Z6+hY0jJ9b99uTORFogaW87OHnvS8lSWRevJPFQrHuivhJsG+1Q4sb+TLrsxIYEhOsMosDUIC9WnRrr5YyolTaU8Ou60JMBmv2R5F7zJBT+q4z0mWdRrPYofT373v4bZt9LuUe5+xxBriZLEIcQ8l4VDA8hfs3mdZ1ja30CHWLHzosiYPEdC4jiQVWFnFILPlaEmXkAzoI90J2J3+tMIe+w==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: keycloak
    type: kubernetes.io/basic-auth

