apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientScope
metadata:
  name: groups
spec:
  forProvider:
    name: groups
    includeInTokenScope: true
    realmIdRef:
      name: vernal
  providerConfigRef:
    name: keycloak-config
