apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: vernal
spec:
  forProvider:
    realm: vernal
    resetPasswordAllowed: true
    smtpServer:
    - auth:
      - passwordSecretRef:
          key: password
          name: smtp-cred
          namespace: keycloak
      from: vernal.developer@gmail.com
      host: smtp.gmail.com
      port: "587"
    displayName: Vernal - SSO
    displayNameHtml: <div class="kc-logo-text"><span>Vernal - SSO</span></div>
    enabled: true
  providerConfigRef:
    name: keycloak-config
