apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: vernal
spec:
  forProvider:
    realm: vernal
    smtpServer:
    - auth:
      - passwordSecretRef:
          key: password
          name: smtp-cred
          namespace: keycloak
        username: "vernal.developer@gmail.com"
      from: "vernal.developer@gmail.com"
      host: smtp.gmail.com
      port: "587"
      starttls: true
    displayName: Vernal - SSO
    displayNameHtml: <div class="kc-logo-text"><span>Vernal - SSO</span></div>
    enabled: true
    registrationAllowed: true
    registrationEmailAsUsername: true
    rememberMe: true
    resetPasswordAllowed: true
  providerConfigRef:
    name: keycloak-config
