apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: argocd-admins
spec:
  forProvider:
    name: argocd-admins
    realmIdRef:
      name: vernal
  providerConfigRef:
    name: keycloak-config
