apiVersion: vernal.dev/v1alpha1
kind: Application
metadata:
  name: test-0
spec:
  owner: group-default-guests
  repo:
    url: https://github.com/vernaldev/vernal
    revision: main
    path: /
  components:
    - name: backend
      image: ghcr.io/vernaldev/test-0_backend:latest
      containerPort: 3001
    - name: frontend
      image: ghcr.io/vernaldev/test-0_frontend:latest
      containerPort: 3000
  postgres:
    enabled: true
    urlEnvVar: DATABASE_URL
  redis:
    enabled: false
    urlEnvVar: REDIS_URL
