apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCVPsPnOI/KSWEo+hWxC2qwnFyqYykaYnpmVlr+qQF0HWCzKAuLHzskPhyUd49Z4jAN5JO7x+110DqwdWGtOWtYVj+t4m2V8Hxm/0EP7+cPOjh5zfBa7y40vikwBr/EcEwiCqzIzYFgFE26WDGLPCWz6mz6ktaAomqyE90QHnc2/Bi4oLTV5B/i6bXUeI3CyeP8F4Lqk6CTDwFCITSmWspMaqzAUjiZlUudVyiZRjH+dyvvSmRWpBq6mqO1blDGr9jJxayQUU7JwYDZUok8Xo/V3xRfpZ3AawUAEuUOHPZ0jz3iyrAyeOO3xiB8Y98RtdCFenfLG9gUQA+4Ftil+gVmNU7DVW0tXFhVo2mrELNvLaHBXu62K0aOgPILD50VZz1e6/7lYmf1qj08Jx7uyCih9iWgJ20JMqK3gfzkTOMTuouGn3rcCjqwDa4w6NxH0SwcyoidhraLJ8RRZ9XEDYR/5hFo+Hb7ULIeBpXydarmgpwvTe4MdEVpcv9/AEUDdfhVCa10XsennBj0iHPK2HmlQqZa+wcgLsla9HU7Adt9oRutThsn8xPo97Sd6z4UAInBgrfdEQYnmHWUQbhnzAv+1YMjENrTqd9fI5is91+Fzt7psn5IRLhHE1yy5x6NS2iSxan91GjpAPfI1RW0YTKysna3Ss9HZfmvDcT22A3F3VMphwv0PJbGL+XzF67I3eYQATJhZamr5SqEAo/5G2Ut7IJHDWVtr7fYiVZQ1SKy1IM/p4N+FVJO
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

