apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.14.1/cert-manager.yaml
- ./local-lan-vernal-dev-tls.sealedsecret.yaml
# - ./certificates
# - ./issuers
# - ./cloudflare.sealedsecret.yaml

patches:
- path: ./namespace.yaml
