apiVersion: vernal.dev/v1alpha1
kind: Application
metadata:
  name: test-app
spec:
  owner: group-default-guests
  repo:
    url: https://github.com/vernaldev/vernal
    revision: main
    path: /
  components:
    - name: backend
      image: ghcr.io/vernaldev/test-app_backend:latest
      containerPort: 4000
    - name: frontend
      image: ghcr.io/vernaldev/test-app_frontend:latest
      containerPort: 3000
