apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./keycloak.provider.yaml
- ./keycloak.runtimeconfig.yaml
- ./namespace.yaml

helmCharts:
- name: crossplane
  namespace: crossplane-system
  releaseName: crossplane
  repo: https://charts.crossplane.io/stable
  valuesFile: values.yaml
  version: 1.14.5
  includeCRDs: true
