apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-secure
  template:
    metadata:
      labels:
        app: keycloak-secure
    spec:
      containers:
      - name: keycloak-secure
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443
        volumeMounts:
        - name: keycloak-secure-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: keycloak-secure-tls
          mountPath: /etc/nginx/ssl
          readOnly: true
      volumes:
      - name: keycloak-secure-config
        configMap:
          name: keycloak-secure-config
      - name: keycloak-secure-tls
        secret:
          secretName: local.lan.vernal.dev-tls
