apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak
resources:
- ./deployment.yaml
- ./service.yaml

configMapGenerator:
- name: keycloak-secure-config
  files:
  - ./nginx.conf
