apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-controller-manager-config
  namespace: cnpg-system
data:
  INHERITED_LABELS: app.kubernetes.io/part-of, app.kubernetes.io/managed-by, backstage.io/kubernetes-id
