apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml

helmCharts:
- includeCRDs: true
  name: loki-stack
  namespace: loki
  releaseName: loki
  repo: https://grafana.github.io/helm-charts
  valuesFile: loki.values.yaml
  version: 2.9.11
